import { StyleSheet, Platform } from "react-native";
import { colors } from "../../../styles/theme";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.gray[50],
    },
    headerGradient: {
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingBottom: 30,
        paddingHorizontal: 20,
        borderBottomLeftRadius: 30,
        borderBottomRightRadius: 30,
    },
    headerContent: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.white,
    },
    headerSubtitle: {
        fontSize: 14,
        color: 'rgba(255, 255, 255, 0.8)',
        marginTop: 4,
    },
    myInscricoesButton: {
        backgroundColor: colors.white,
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 25,
        flexDirection: 'row',
        alignItems: 'center',
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    myInscricoesText: {
        color: colors.primary[700],
        fontSize: 13,
        fontWeight: 'bold',
        marginLeft: 6,
    },
    listContainer: {
        padding: 20,
        paddingBottom: 100,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.gray[800],
        marginBottom: 16,
    },
    eventCard: {
        backgroundColor: colors.white,
        borderRadius: 16,
        marginBottom: 20,
        overflow: 'hidden',
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
    },
    bannerContainer: {
        width: '100%',
        height: 160,
    },
    eventBanner: {
        width: '100%',
        height: '100%',
        resizeMode: 'cover',
    },
    dateBadge: {
        position: 'absolute',
        top: 12,
        left: 12,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
        alignItems: 'center',
    },
    dateDay: {
        color: colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    dateMonth: {
        color: colors.white,
        fontSize: 10,
        fontWeight: '600',
        textTransform: 'uppercase',
    },
    eventContent: {
        padding: 16,
    },
    eventTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.gray[900],
        marginBottom: 8,
    },
    eventInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    eventInfoText: {
        fontSize: 13,
        color: colors.gray[600],
        marginLeft: 6,
    },
    eventFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: colors.gray[100],
    },
    statusBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
    },
    statusText: {
        fontSize: 11,
        fontWeight: '700',
    },
    detailButton: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    detailButtonText: {
        color: colors.primary[600],
        fontSize: 14,
        fontWeight: '600',
        marginRight: 4,
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 60,
    },
    emptyText: {
        fontSize: 16,
        color: colors.gray[400],
        marginTop: 12,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.gray[50],
    },
    // Detail Styles
    fullBanner: {
        width: '100%',
        height: 250,
    },
    backButtonFloating: {
        position: 'absolute',
        top: Platform.OS === 'ios' ? 60 : 40,
        left: 20,
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    detailContainer: {
        flex: 1,
        backgroundColor: colors.white,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        marginTop: -30,
        padding: 24,
    },
    titleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 16,
    },
    detailTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: colors.gray[900],
        flex: 1,
        marginRight: 10,
    },
    infoBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.gray[50],
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
        marginBottom: 12,
    },
    infoBadgeText: {
        fontSize: 14,
        color: colors.gray[700],
        marginLeft: 8,
    },
    descriptionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.gray[800],
        marginTop: 20,
        marginBottom: 8,
    },
    descriptionText: {
        fontSize: 15,
        color: colors.gray[600],
        lineHeight: 22,
    },
    subEventTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.gray[800],
        marginTop: 30,
        marginBottom: 12,
    },
    subEventCard: {
        flexDirection: 'row',
        backgroundColor: colors.gray[50],
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
    },
    subEventInfo: {
        flex: 1,
    },
    subEventTitleText: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.gray[900],
        marginBottom: 4,
    },
    subEventDetail: {
        fontSize: 12,
        color: colors.gray[500],
    },
    vagasBadge: {
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        marginTop: 8,
        alignSelf: 'flex-start',
    },
    vagasText: {
        fontSize: 11,
        color: colors.primary[600],
        fontWeight: '600',
    },
    floatingFooter: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        padding: 20,
        paddingBottom: Platform.OS === 'ios' ? 40 : 20,
        backgroundColor: colors.white,
        borderTopWidth: 1,
        borderTopColor: colors.gray[100],
    },
    registerButton: {
        backgroundColor: colors.primary[600],
        borderRadius: 16,
        paddingVertical: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    registerButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    alreadyRegisteredBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(34, 197, 94, 0.1)',
        borderRadius: 12,
        paddingVertical: 12,
        borderWidth: 1,
        borderColor: 'rgba(34, 197, 94, 0.2)',
    },
    alreadyRegisteredText: {
        color: '#166534',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
    // Inscrições Styles
    inscricaoCard: {
        backgroundColor: colors.white,
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        borderLeftWidth: 6,
        borderLeftColor: colors.primary[600],
        elevation: 3,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    inscricaoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    inscricaoTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: colors.gray[900],
        flex: 1,
        marginRight: 10,
    },
    inscricaoStatusBadge: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    inscricaoStatusText: {
        fontSize: 10,
        fontWeight: 'bold',
        textTransform: 'uppercase',
    },
    inscricaoInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    inscricaoInfoText: {
        fontSize: 14,
        color: colors.gray[500],
        marginLeft: 6,
    },
    inscricaoFooter: {
        flexDirection: 'row',
        marginTop: 20,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: colors.gray[100],
        justifyContent: 'space-between',
    },
    certificateButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primary[50],
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 12,
    },
    certificateButtonText: {
        color: colors.primary[700],
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
    detailsLink: {
        justifyContent: 'center',
    },
    detailsLinkText: {
        color: colors.gray[400],
        fontSize: 14,
        fontWeight: '500',
    },
    tabBar: {
        flexDirection: 'row',
        backgroundColor: colors.white,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.gray[100],
    },
    tab: {
        flex: 1,
        paddingVertical: 16,
        alignItems: 'center',
        borderBottomWidth: 3,
        borderBottomColor: 'transparent',
    },
    activeTab: {
        borderBottomColor: colors.primary[600],
    },
    tabText: {
        fontSize: 14,
        color: colors.gray[400],
        fontWeight: '600',
    },
    activeTabText: {
        color: colors.primary[600],
    },
});
